sudo: required
dist: trusty
language: cpp

cache:
  apt: true

matrix:
  include:

    # Linux GCC 5 & 6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # # Linux Clang 3.7 & 3.89
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.7
    #       packages:
    #         - clang-3.7
    #   env:
    #     - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7 && EXTRA_CXXFLAGS=-stdlib=libc++"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.8
    #       packages:
    #         - clang-3.8
    #   env:
    #     - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8 && EXTRA_CXXFLAGS=-stdlib=libc++"

    # # OSX GCC 5 & 6
    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

    # OSX Clang
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh scripts/setup-osx.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/setup-linux.sh ; fi

script:
  - echo $EXTRA_CXXFLAGS
  - make re
